environments:
  development:
    values:
      - replicaCount: 1
      - image:
          tag: "latest"
      - ingress:
          enabled: true
          host: dev.example.com

---
releases:
  # Pre-install chart - sets up prerequisites
  - name: pre-install
    namespace: dev-appender-java
    createNamespace: true
    chart: ../../charts/pre-install
    values:
      - ../../values/pre-install/values.dev.yaml


  # Appender Java application
  - name: appender-java
    namespace: dev-appender-java
    createNamespace: true
    chart: ../../charts/appender-java
    needs:
      - dev-appender-java/pre-install


