apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appender-java-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/your-infrastructure-repo
    targetRevision: HEAD
    path: cluster-a/helmfile/environments/production
  destination:
    server: https://kubernetes.default.svc
    namespace: appender-java-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 