# # #########################################################################
# # # Production Configuration for Loki with S3 Storage
# # #########################################################################

# # Production-specific overrides
# loki:
#   # Production storage configuration
#   storage:
#     type: s3
#     aws:
#       s3: s3://your-loki-bucket
#       region: eu-central-1
#       # Add your AWS credentials or use IAM roles
#       # access_key_id: YOUR_ACCESS_KEY
#       # secret_access_key: YOUR_SECRET_KEY
  
#   # Production limits
#   limits_config:
#     volume_max_series: 10000  # Higher for production
#     retention_period: 720h    # 30 days retention
#     reject_old_samples: true
#     reject_old_samples_max_age: 168h
  
#   # Production performance settings
#   querier:
#     max_concurrent: 8  # Higher for production
  
#   # Production deployment
#   deploymentMode: SimpleScalable

# # Production deployment settings
# backend:
#   replicas: 3
#   resources:
#     requests:
#       memory: "1Gi"
#       cpu: "500m"
#     limits:
#       memory: "2Gi"
#       cpu: "1000m"
# read:
#   replicas: 2
#   resources:
#     requests:
#       memory: "1Gi"
#       cpu: "500m"
#     limits:
#       memory: "2Gi"
#       cpu: "1000m"
# write:
#   replicas: 2
#   resources:
#     requests:
#       memory: "1Gi"
#       cpu: "500m"
#     limits:
#       memory: "2Gi"
#       cpu: "1000m"

# # Disable single binary mode for production
# singleBinary:
#   replicas: 0

# # Production monitoring
# monitoring:
#   dashboards:
#     enabled: true
#     namespace: observability
#     labels:
#       grafana_dashboard: "1"
#   rules:
#     enabled: true
#     alerting: true  # Enable alerts in production
#     namespace: observability
#   serviceMonitor:
#     enabled: true
#     labels:
#       prometheus: prometheus-prometheus
#     interval: 15s  # More frequent scraping in production

# # Enable minio for production (if using S3-compatible storage)
# minio:
#   enabled: false  # Set to true if using MinIO instead of AWS S3
