# otel-config.yaml
# This file is used to configure the OpenTelemetry Collector.
receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: 0.0.0.0:4317
processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 900
exporters:
  debug:
    verbosity: basic
  otlphttp/loki:
    endpoint: http://loki-gateway.observability:80/otlp
    compression: snappy
  otlp/tempo:
    endpoint: tempo.observability:4317
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch, memory_limiter ]
      exporters: [  otlp/tempo ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch, memory_limiter ]
      exporters: [debug]
    logs:
      receivers: [ otlp]
      processors: [ batch, memory_limiter ]
      exporters: [otlphttp/loki, debug]
