repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx


environments:
  dev:
    values:
      - envPrefix: dev-
  prod:
    values:
      - envPrefix: prod-
---
releases:
  - name: "{{ .Values.envPrefix }}ingress-nginx"
    namespace: "{{ .Values.envPrefix }}ingress-nginx"
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    version: 4.12.3
    values:
      - ../../values/nginx/values.yaml 