helmfiles:
  - ./charts/argocd/helmfile.yaml
  - ./charts/nginx/helmfile.yaml
  - ./charts/cert-manager/helmfile.yaml
  - ./charts/opentelemetry-collector-daemonset/helmfile.yaml
  - ./charts/opentelemetry-collector-deployment/helmfile.yaml
  - ./charts/opentelemetry-operator/helmfile.yaml
