repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: jetstack
    url: https://charts.jetstack.io
  - name: opentelemetry-helm
    url: https://open-telemetry.github.io/opentelemetry-helm-charts

releases:
  # ArgoCD - GitOps Continuous Delivery
  - name: argocd
    namespace: argocd
    createNamespace: true
    chart: argo/argo-cd
    version: 5.51.6
    values:
      - server:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - argocd.example.com
            tls:
              - secretName: argocd-server-tls
                hosts:
                  - argocd.example.com
          extraArgs:
            - --insecure
        configs:
          secret:
            argocdServerAdminPassword: "$2a$10$YourHashedPasswordHere"
        dex:
          enabled: false
        redis:
          enabled: true
        repoServer:
          serviceAccount:
            create: true
        applicationSet:
          enabled: true

  # Ingress Controller
  - name: ingress-nginx
    namespace: ingress-nginx
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    version: 4.7.1
    values:
      - controller:
          service:
            type: LoadBalancer
          replicaCount: 1

  # cert-manager
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: v1.18.1
    set:
      - name: installCRDs
        value: true

  # OpenTelemetry Collector
  - name: opentelemetry-collector
    namespace: observability
    createNamespace: true
    chart: opentelemetry-helm/opentelemetry-collector
    version: 0.127.2
    needs:
      - cert-manager/cert-manager
    values:
      - ./values/otel-collector/values.yaml

  # OpenTelemetry Operator
  - name: opentelemetry-operator
    namespace: observability
    createNamespace: true
    chart: opentelemetry-helm/opentelemetry-operator
    version: 0.90.4
    needs:
      - cert-manager/cert-manager
    values:
          - ./values/otel-operator/values.yaml
