{
 "title": "Alerts Details",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname!=\"DeadMansSwitch\", alertstate=\"firing\"}>0 OR on() vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname!=\"DeadMansSwitch\", alertstate=\"firing\", severity=\"critical\"}>0 OR on() vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname!=\"DeadMansSwitch\", alertstate=\"firing\"}>0 OR on() vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Warning",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname!=\"DeadMansSwitch\", alertstate=\"firing\", severity=\"warning\"}>0 OR on() vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Info",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname!=\"DeadMansSwitch\", alertstate=\"firing\", severity=\"info\"}>0 OR on() vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alert rule definition",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_rule_group_rules{rule_group!~\".+recording.+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "None",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname!=\"DeadMansSwitch\", alertstate=\"firing\", severity=\"none\"}>0 OR on() vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alert List", "type": "alertlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Firing Alerts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", alertname != \"Watchdog\" }) by (alertname)",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "Pending Alerts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"pending\", alertname != \"Watchdog\" }) by (alertname)",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "Firing",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(ALERTS{alertname!=\"DeadMansSwitch\",alertstate=\"firing\"})>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ALERTS{alertname!=\"DeadMansSwitch\", alertstate=\"pending\"}> 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}