{
 "title": "Application logs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {}
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"flexrouter\", job=\"kube-state-metrics\", container!=\"''\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"flexrouter\", job=\"kube-state-metrics\", pod=\"$pod\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Simple OFP Fix Gateway 1",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"simple-ofp-fix-gateway-ofp1\"} |= ``"
    }
   ]
  },
  {
   "title": "OTC Fix Gateway 1",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"otc-fix-gateway-otc1\"} |= \"\""
    }
   ]
  },
  {
   "title": "Simple OFP Fix Gateway 2",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"simple-ofp-fix-gateway-ofp2\"} |= ``"
    }
   ]
  },
  {
   "title": "OTC Fix Gateway 2",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "{app=\"otc-fix-gateway-otc2\"} |= ``"
    }
   ]
  },
  {
   "title": "CDX Fix Gateway",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{app=\"otc-fix-gateway-cdx1\"} |= ``"
    }
   ]
  },
  {
   "title": "Trade Rebel Fix Gateway",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "{app=\"otc-fix-gateway-trbl1\"} |= ``"
    }
   ]
  },
  {
   "title": "Neucatt",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{job=\"neucatt\"}"
    }
   ]
  },
  {
   "title": "Neucatt App Log",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "{job=\"neucatt-app-log\"}"
    }
   ]
  },
  {
   "title": "Appia",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "{job=\"appia-file-logs\"}"
    }
   ]
  },
  {
   "title": "Configuration service",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "{job=\"configuration-service\"} |= ``",
     "maxLines": 100
    }
   ]
  }
 ]
}