{
 "title": "Custom Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(flexrouter_message_appia_total,service)"
    }
   },
   {
    "name": "source",
    "label": "Source",
    "query": {
     "query": "label_values(flexrouter_message_appia_total{service=~\"$service\"},source)"
    }
   },
   {
    "name": "target",
    "label": "Target",
    "query": {
     "query": "label_values(flexrouter_message_appia_total{service=~\"$service\", source=~\"$source\"},target)"
    }
   },
   {
    "name": "destination",
    "label": "Destination",
    "query": {
     "query": "label_values(flexrouter_message_appia_total{service=~\"$service\", source=~\"$source\", target=~\"$target\"},destination)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Messages sent from Brokers in 24h",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(flexrouter_message_appia_total{service=~\"$service\",instance!=\"\"}[24h]))",
     "legendFormat": "Service: {{service}} -> source: {{source}} -> Target: {{target}} -> Destination: {{destination}}"
    }
   ]
  },
  {
   "title": "Rate of Messages sent from Brokers per sec",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(flexrouter_message_appia_total{service=~\"simple-ofp.*\"}[5m]))",
     "legendFormat": "Instance: {{job}} -> source: {{source}} -> Target: {{target}} -> Destination: {{destination}}"
    }
   ]
  },
  {
   "title": "Top 3 Messages sent by criteria in 24h",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, sum(increase(flexrouter_message_appia_total{service=~\"$service\", source=~\"$source\", target=~\"$target\" ,instance!=\"\"}[24h])) by (service, source, target, destination ))",
     "legendFormat": "Service: {{service}}, source: {{source}}, Target: {{target}}, Dest: {{destination}}"
    }
   ]
  },
  {
   "title": "Messages sent for the 24h",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "increase(flexrouter_message_appia_total{job=~\"$instance\", source=~\"$source\", target=~\"$target\", destination=~\"$destination\"}[24h])",
     "legendFormat": "instance: {{job}}, Source: {{source}}, Target: {{target}}, Dest: {{destination}}"
    }
   ]
  },
  {
   "title": "Messages sent by criteria in 24h",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(flexrouter_message_appia_total{service=~\"$service\", source=~\"$source\", target=~\"$target\", instance!=\"\"}[24h])) by (service, source, target, destination )",
     "legendFormat": "Service: {{service}}, source: {{source}}, Target: {{target}}, Dest: {{destination}}"
    }
   ]
  }
 ]
}