{
 "title": "EKS Cluster Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Node",
    "label": "node",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   },
   {
    "name": "running_otc_instances",
    "query": {
     "query": "query_result(sum(label_replace(min_over_time(kube_pod_status_ready{condition=\"true\", namespace=\"flexrouter\", pod=~\"otc-fix-gateway-.*\"}[$__range]), \"instance_type\", \"$1\", \"pod\", \"otc-fix-gateway-(.*?)-.*\")))"
    }
   },
   {
    "name": "total_otc_instances",
    "query": {
     "query": "query_result(count(kube_deployment_created{namespace=\"flexrouter\", deployment=~\"otc-fix-gateway.*\"}))"
    }
   },
   {
    "name": "running_config_service_instances",
    "query": {
     "query": "query_result(sum(kube_pod_status_ready{namespace=\"flexrouter\",pod=~\"configuration-service.*\", condition=\"true\"}))"
    }
   },
   {
    "name": "total_ofp_instances",
    "query": {
     "query": "query_result(count(kube_deployment_created{namespace=\"flexrouter\", deployment=~\"simple-ofp-fix-gateway.*\"}))"
    }
   },
   {
    "name": "total_config_service_instances",
    "query": {
     "query": "query_result(count(kube_deployment_created{namespace=\"flexrouter\", deployment=~\"configuration-service.*\"}))"
    }
   },
   {
    "name": "running_ofp_instances",
    "query": {
     "query": "query_result(sum(label_replace(min_over_time(kube_pod_status_ready{condition=\"true\", namespace=\"flexrouter\", pod=~\"simple-ofp-fix-gateway-.*\"}[$__range]), \"instance_type\", \"$1\", \"pod\", \".*-(ofp[0-9]+)-.*\")))"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kubelet_volume_stats_inodes,instance)"
    }
   },
   {
    "name": "persistentvolumeclaim",
    "label": "persistentvolumeclaim",
    "query": {
     "query": "label_values(kubelet_volume_stats_inodes{namespace=\"$namespace\", instance=\"$instance\"},persistentvolumeclaim)"
    }
   },
   {
    "name": "total_traderbl_instances",
    "query": {
     "query": "query_result(count(kube_deployment_created{namespace=\"flexrouter\", deployment=~\"otc-fix-gateway-trbl.*\"}))"
    }
   },
   {
    "name": "running_traderbl_instances",
    "query": {
     "query": "query_result(sum(kube_pod_status_ready{namespace=\"flexrouter\",pod=~\"otc-fix-gateway-trbl.*\", condition=\"true\"}))"
    }
   },
   {
    "name": "pod_ofp1",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"flexrouter\", pod=~\"simple-ofp-fix-gateway-ofp1-.*\"},pod)"
    }
   },
   {
    "name": "trade_rebel",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"flexrouter\", pod=~\"otc-fix-gateway-trbl1.*\"},pod)"
    }
   },
   {
    "name": "pod_ofp2",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"flexrouter\", pod=~\"simple-ofp-fix-gateway-ofp2-.*\"},pod)"
    }
   },
   {
    "name": "pod_otc1",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"flexrouter\", pod=~\"otc-fix-gateway-otc1-.*\"},pod)"
    }
   },
   {
    "name": "pod_otc2",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"flexrouter\", pod=~\"otc-fix-gateway-otc2-.*\"},pod)"
    }
   },
   {
    "name": "pod_cdx",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"flexrouter\", pod=~\"otc-fix-gateway-cdx1-.*\"},pod)"
    }
   },
   {
    "name": "pod_confser",
    "label": "pod_confser",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"flexrouter\", pod!~\"configuration-service-ui-.*\", pod=~\"configuration-service-.*\"},pod)"
    }
   },
   {
    "name": "pod_trbl",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"flexrouter\", pod=~\"otc-fix-gateway-trbl1.*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1- avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} - node_memory_MemFree_bytes{job=\"node-exporter\"} - node_memory_Cached_bytes{job=\"node-exporter\"} - node_memory_Buffers_bytes{job=\"node-exporter\"})) / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Disk Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1- (sum(node_filesystem_avail_bytes{job=\"node-exporter\", device!~\"/dev/loop.*\",  device!=\"gvfsd-fuse\",device!~\"tmpfs | nsfs\", device!=\"shm\"})/sum(node_filesystem_size_bytes{job=\"node-exporter\", device!~\"/dev/loop.*\",  device!=\"gvfsd-fuse\",device!~\"tmpfs | nsfs\", device!=\"shm\"}))"
    }
   ]
  },
  {
   "title": "Infrastructure services",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{namespace=\"observability\",pod=~\"prometheus-prometheus.*\"}[$__range]))",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "min_over_time(kube_pod_container_status_ready{namespace=\"keycloak\", pod=~\"keycloak.*\"}[$__range])",
     "legendFormat": "Keycloak"
    },
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{pod=~\"tempo-.*\"}[$__range]))",
     "legendFormat": "Tempo"
    },
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{namespace=\"dapr-system\", pod=~\"dapr-operator.*\"}[$__range])) ",
     "legendFormat": "Dapr"
    },
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{pod=~\"rabbitmq.*\", container=\"rabbitmq\"}[$__range]))",
     "legendFormat": "Rabbitmq"
    },
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{namespace=\"observability\", pod=~\"loki.*\"}[$__range]))",
     "legendFormat": "Loki"
    },
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{namespace=\"argocd\", pod=~\"argocd.*\", pod!~\"argocd-redis-secret.*\"}[$__range]))",
     "legendFormat": "Argocd"
    },
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{namespace=\"cert-manager\", pod=~\"cert-manager.*\"}[$__range]))",
     "legendFormat": "Cert-manager"
    },
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{namespace=\"observability\", pod=~\"opentelemetry-collector.*\"}[$__range]))",
     "legendFormat": "Otel-collector"
    },
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{namespace=\"observability\", pod=~\"kubecost.*\"}[$__range]))",
     "legendFormat": "Kubecost"
    },
    {
     "expr": "min(min_over_time(kube_pod_status_ready{condition=\"true\", pod=~\"spring-boot-admin-service.*\"}[$__range]))",
     "legendFormat": "Spring Boot Admin"
    }
   ]
  },
  {
   "title": "Application",
   "type": "stat",
   "description": "We need to create dynamic pod variables instead",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{namespace=\"flexrouter\", pod=~\"simple-ofp-fix-gateway.*\"}[$__range]))",
     "legendFormat": "Simple OFP Fix Gateway: $running_ofp_instances / $total_ofp_instances"
    },
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{namespace=\"flexrouter\", pod=~\"otc-fix-gateway.*\"}[$__range]))",
     "legendFormat": "OTC Fix Gateway: $running_otc_instances / $total_otc_instances"
    }
   ]
  },
  {
   "title": "Simple OFP Fix Gateway",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "min(label_replace(min_over_time(kube_pod_status_ready{condition=\"true\", namespace=\"flexrouter\", pod=~\"simple-ofp-fix-gateway-.*\"}[$__range]), \"instance_type\", \"$1\", \"pod\", \".*-(ofp[0-9]+)-.*\")) by (pod, instance_type)",
     "legendFormat": "{{instance_type}}"
    }
   ]
  },
  {
   "title": "Configuration Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(kube_pod_status_ready{condition=\"true\", namespace=\"flexrouter\", pod=~\"configuration-service-.*\", pod!~\"configuration-service-ui-.*\"}[$__range]))",
     "legendFormat": "Configuration"
    },
    {
     "expr": "min(min_over_time(kube_pod_status_ready{condition=\"true\", namespace=\"flexrouter\", pod=~\"configuration-service-ui-.*\"}[$__range]))",
     "legendFormat": "Configuration UI"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[5m]))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"})",
     "legendFormat": "Limit"
    },
    { "expr": "sum (machine_cpu_cores)", "legendFormat": "Total capacity" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} - node_memory_MemFree_bytes{job=\"node-exporter\"} - node_memory_Cached_bytes{job=\"node-exporter\"} - node_memory_Buffers_bytes{job=\"node-exporter\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{job=\"node-exporter\", device!~\"/dev/loop.*\", device!=\"gvfsd-fuse\", device!~\"shm\"} - node_filesystem_free_bytes{job=\"node-exporter\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{job=\"node-exporter\", device!~\"/dev/loop.*\",  device!=\"gvfsd-fuse\",device!~\"shm\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "OTC FIX Gateway",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "min(label_replace(min_over_time(kube_pod_status_ready{condition=\"true\", namespace=\"flexrouter\", pod=~\"otc-fix-gateway-.*\"}[$__range]), \"instance_type\", \"$1\", \"pod\", \"otc-fix-gateway-(.*?)-.*\")) by (pod, instance_type)",
     "legendFormat": "{{instance_type}}"
    }
   ]
  },
  {
   "title": "Cluster CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(1- avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} - node_memory_MemFree_bytes{job=\"node-exporter\"} - node_memory_Cached_bytes{job=\"node-exporter\"} - node_memory_Buffers_bytes{job=\"node-exporter\"})) / sum(node_memory_MemTotal_bytes))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "(1- (sum(node_filesystem_avail_bytes{job=\"node-exporter\", device!~\"/dev/loop.*\",  device!=\"gvfsd-fuse\",device!~\"tmpfs | nsfs\", device!=\"shm\"})/sum(node_filesystem_size_bytes{job=\"node-exporter\", device!~\"/dev/loop.*\",  device!=\"gvfsd-fuse\",device!~\"tmpfs | nsfs\", device!=\"shm\"})))*100"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total[5m]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total[5m]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Traces - Fix messages",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "filters": [
      { "id": "af6f80ee", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=~",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "simple-ofp-fix-gateway-ofp2" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "!=",
       "scope": "span",
       "tag": "name",
       "value": [ "GET" ],
       "valueType": "string"
      }
     ],
     "limit": 50000,
     "spss": 10,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Log rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate({namespace=\"flexrouter\", container!~\"configuration-service-container|configuration-service-ui-container\"} [$__auto])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Infrastructure pods Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"rabbitmq|observability|dapr-system|cert-manager|keycloak|postgresql\", phase=\"Running\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"rabbitmq|observability|dapr-system|cert-manager|keycloak|postgresql\", phase=\"Pending\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"rabbitmq|observability|dapr-system|cert-manager|keycloak|postgresql\", phase=\"Failed\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"rabbitmq|observability|dapr-system|cert-manager|keycloak|postgresql\", phase=\"Succeeded\"})",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"rabbitmq|observability|dapr-system|cert-manager|keycloak|postgresql\", phase=\"Unknown\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Application pods Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"flexrouter\", phase=\"Running\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"flexrouter\", phase=\"Pending\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"flexrouter\", phase=\"Failed\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"flexrouter\", phase=\"Succeeded\"})",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"flexrouter\", phase=\"Unknown\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Application Service Status History",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " min(min_over_time(kube_pod_container_status_ready{namespace=\"flexrouter\", pod=~\"otc-fix-gateway.*\"}[1m]))",
     "legendFormat": "OTC Fix Gateway OTC 1"
    },
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{namespace=\"flexrouter\", pod=~\"simple-ofp-fix-gateway.*\"}[1m]))",
     "legendFormat": "OFP Fix Gateway 1"
    },
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{namespace=\"flexrouter\", pod=~\"configuration-service.*\", pod!~\"configuration-service-ui-.*\"}[1m]))",
     "legendFormat": "Configuration Service"
    },
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{namespace=\"flexrouter\", pod!~\"configuration-service.*\", pod=~\"configuration-service-ui-.*\"}[1m]))",
     "legendFormat": "Configuration UI Service"
    }
   ]
  },
  {
   "title": "Infrastructure Services Status History",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{namespace=\"observability\",pod=~\"prometheus.*\"}[1m]))",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{namespace=\"keycloak\", pod=~\"keycloak.*\"}[1m]))",
     "legendFormat": "Keycloak"
    },
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{namespace=\"dapr-system\", pod=~\"dapr.*\"}[1m]))",
     "legendFormat": "Dapr"
    },
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{namespace=\"observability\", pod=~\"loki.*\"}[1m]))",
     "legendFormat": "Loki"
    },
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{namespace=\"observability\", pod=~\"tempo.*\",}[1m]))",
     "legendFormat": "Tempo"
    },
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{namespace=\"rabbitmq-system\", pod=~\"rabbitmq.*\"}[1m]))",
     "legendFormat": "Rabbitmq"
    },
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{namespace=\"argocd\", pod=~\"argocd.*\", pod!~\"argocd-redis-secret-init.*\"}[1m]))",
     "legendFormat": "Argocd"
    },
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{namespace=\"cert-manager\", pod=~\"cert-manager.*\"}[1m]))",
     "legendFormat": "Cert-manager"
    },
    {
     "expr": "min(min_over_time(kube_pod_container_status_ready{namespace=\"observability\", pod=~\"opentelemetry-collector.*\"}[1m]))",
     "legendFormat": "Otel-collector"
    }
   ]
  },
  {
   "title": "Application Pods  Cpu / Disk / Memory / Network Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_usage_seconds_total{namespace=\"flexrouter\"}[$__range])) by (pod)",
     "legendFormat": "Cores"
    },
    {
     "expr": "sum(increase(container_memory_usage_bytes{namespace=\"flexrouter\"}[$__range])) by (pod)",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "sum( increase(container_fs_reads_bytes_total{namespace=~\"flexrouter\",container!=\"POD\"}[$__range])) by (pod) + sum(increase(container_fs_writes_bytes_total{namespace=~\"flexrouter\",container!=\"POD\"}[$__range])) by (pod) ",
     "legendFormat": "Disk "
    },
    {
     "expr": "sum(increase(container_network_receive_bytes_total{namespace=\"flexrouter\"}[$__range])) by (pod)",
     "legendFormat": "Received Bytes"
    },
    {
     "expr": "sum(increase(container_network_transmit_bytes_total{namespace=~\"flexrouter\"}[$__range])) by (pod)",
     "legendFormat": "Transmitted Bytes"
    }
   ]
  },
  {
   "title": "Infrastructure Pods  Cpu / Disk / Memory / Network Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"rabbitmq-system|observability|dapr-system|cert-manager|keycloak|postgresql\",container!=\"POD\"}[$__range])) by (pod)",
     "legendFormat": "Cores"
    },
    {
     "expr": "sum(rate(container_memory_usage_bytes{namespace=~\"rabbitmq-system|observability|dapr-system|cert-manager|keycloak|postgresql\",container!=\"POD\"}[$__range])) by (pod)",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "sum( rate(container_fs_reads_bytes_total{namespace=~\"rabbitmq-system|observability|dapr-system|cert-manager|keycloak|postgresql\",container!=\"POD\"}[$__range])) by (pod) + sum(rate(container_fs_writes_bytes_total{namespace=~\"rabbitmq-system|observability|dapr-system|cert-manager|keycloak|postgresql\",container!=\"POD\"}[$__range])) by (pod) ",
     "legendFormat": "Disk"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"rabbitmq-system|observability|dapr-system|cert-manager|keycloak|postgresql\"}[$__range])) by (pod)",
     "legendFormat": "Received Bytes"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"rabbitmq-system|observability|dapr-system|cert-manager|keycloak|postgresql\"}[$__range])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node details & Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Nodes CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{container=\"node-exporter\"}) by (instance) - sum(node_memory_MemFree_bytes{container=\"node-exporter\"}) by (instance) - sum(node_memory_Cached_bytes{container=\"node-exporter\"}) by (instance) - sum(node_memory_Buffers_bytes{container=\"node-exporter\"}) by (instance)) / sum(node_memory_MemTotal_bytes{container=\"node-exporter\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nodes Disk Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - ((sum(node_filesystem_free_bytes{mountpoint=~\"/\"}) by (instance) / sum(node_filesystem_size_bytes{mountpoint=~\"/\"}) by (instance)) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 11, "w": 6, "x": 18, "y": 39 } },
  {
   "title": " Node details ",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\"}) by (node)",
     "legendFormat": "pod core "
    },
    {
     "expr": "sum(kube_node_status_allocatable{job=\"kube-state-metrics\", resource=\"ephemeral_storage\", unit=\"byte\"}) by (node)",
     "legendFormat": "ephemeral storage"
    },
    {
     "expr": "sum(kube_node_status_allocatable{job=\"kube-state-metrics\", resource=\"memory\", unit=\"byte\"}) by (node)",
     "legendFormat": "allocated memory"
    },
    {
     "expr": "(sum(kube_node_status_allocatable{job=\"kube-state-metrics\", resource=\"cpu\", unit=\"core\"}) by (node)) ",
     "legendFormat": "allocated memory"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\"}[5m])) by (node)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=\"kubelet\"}[5m])) by (node)",
     "legendFormat": "Transmit Rate"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\"}) by (node)",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{job=\"kubelet\"}[5m])) by (node)"
    }
   ]
  },
  { "title": "Kubernetes overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Deployments",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available)",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(kube_deployment_status_replicas)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stateful Sets",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_available)",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(kube_statefulset_status_replicas)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"apiserver\",code=~\"2..\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "K8s API Server: Error Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"apiserver\",code=~\"[45]..\"}[5m]))*100/sum(rate(apiserver_request_total{job=\"apiserver\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "K8s API Server: Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\", verb!=\"CONNECT\", verb!=\"WATCH\"}[5m])) by (verb, le))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Replica Sets",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_replicaset_status_ready_replicas)",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(kube_replicaset_status_replicas)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Daemon Sets",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_desired_number_scheduled ) by (phase)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Cron Jobs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_cronjob_created)", "legendFormat": "Created" },
    {
     "expr": "sum(kube_cronjob_status_active)",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_job_status_active)", "legendFormat": "Active" },
    { "expr": "sum(kube_job_status_succeeded)", "legendFormat": "Succeeded" },
    { "expr": "sum(kube_job_status_failed)", "legendFormat": "Failed" }
   ]
  },
  {
   "title": "Kubernetes Events",
   "type": "logs",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 59 },
   "targets": [
    {
     "expr": "{job=\"kube-system/eventrouter\"} |= ``"
    }
   ]
  }
 ]
}