{
 "title": "Kubernetes Events",
 "description": "Kubernetes Events from EventRouter",
 "tags": [
  "loki",
  "events",
  "kubernetes",
  "logs"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "cluster_name",
    "query": {}
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {}
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {}
   },
   {
    "name": "container",
    "label": "container",
    "query": {}
   },
   {
    "name": "kind",
    "label": "kind",
    "query": {}
   },
   {
    "name": "type",
    "label": "type",
    "query": {}
   },
   {
    "name": "reason",
    "label": "reason",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Reason", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Image Pull Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"eventrouter\", reason=~\"Failed.*\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\", kind=~\"$kind\", type=~\"$type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Container Crashed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"eventrouter\", reason=~\".*BackOff.*\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\", kind=~\"$kind\", type=~\"$type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Container OOM Killed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"eventrouter\", reason=\"OOMKilling\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\", kind=~\"$kind\", type=~\"$type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Pod Evicted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"eventrouter\", reason=\"TaintManagerEviction\"} |= \"Marking for deletion Pod\"| logfmt | __error__=\"\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Schedule Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"eventrouter\", reason=\"FailedScheduling\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\", kind=~\"$kind\", type=~\"$type\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Liveness Check Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"eventrouter\", reason=\"Killing\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\", kind=~\"$kind\", type=~\"$type\"} [$__interval]))"
    }
   ]
  },
  { "title": "Timeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Events Timeline by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by(namespace) (count_over_time({namespace=~\"$namespace\", pod=~\"$pod\", kind=~\"$kind\", reason=~\"$reason\", type=~\"$type\"} |= `` [$__interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type) (count_over_time({job=\"kube-system/eventrouter\"} | __error__=\"\" [$__interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"kube-system/eventrouter\"} | type = \"Warning\" | __error__=\"\" [$__interval]))",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "By Kind",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({job=\"kube-system/eventrouter\"}| __error__=\"\"[$__interval])) by (kind)",
       "legendFormat": "{{source_component}}"
      }
     ]
    },
    {
     "title": "By Namespace",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({job=\"kube-system/eventrouter\"}| __error__=\"\"[$__interval])) by (namespace)",
       "legendFormat": "{{involvedObject_kind}}"
      }
     ]
    },
    {
     "title": "By Type",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({job=\"kube-system/eventrouter\"}| __error__=\"\"[$__interval])) by (type)",
       "legendFormat": "{{involvedObject_kind}}"
      }
     ]
    },
    {
     "title": "By Cluster",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 18, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({job=\"kube-system/eventrouter\"}| __error__=\"\"[$__interval])) by (cluster_name)",
       "legendFormat": "{{involvedObject_kind}}"
      }
     ]
    },
    {
     "title": "TOP 10  Kubernetes Events",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "topk(10,sum by (reason) (count_over_time({job=\"kube-system/eventrouter\"} | __error__=\"\"[$__interval])))",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "TOP 10  Kubernetes Namespaces in Events",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "topk(10,sum by (namespace) (count_over_time({job=\"kube-system/eventrouter\"} | __error__=\"\"[$__interval])))",
       "legendFormat": "{{reason}}"
      }
     ]
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Kubernetes Events",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{job=\"kube-system/eventrouter\", cluster_name=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\", kind=~\"$kind\", reason=~\"$reason\", type=~\"$type\"} |= ``"
    }
   ]
  }
 ]
}