{
 "title": "Kubernetes Logs",
 "description": "Logs collected from Kubernetes, stored in Loki",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "query", "label": "Search Query" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "stream",
    "query": {}
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_container_info{job=\"kube-state-metrics\", namespace=\"$namespace\", container!=\"''\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pod\"},container)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(kube_pod_container_info{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pod\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$query count log file",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(count_over_time({ job =~\"$job.*\"} |= \"$query\" [$__interval])) ",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "CPU Usage in Cores with Requests and limit",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"flexrouter\", container!=\"POD\", pod=~\"$pod\", container=~\"$container\"}[1m])) by (pod, container)",
     "legendFormat": " value"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=~\"flexrouter\", pod=~\"$pod\", resource=\"cpu\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=~\"flexrouter\", container!=\"POD\", pod=~\"$pod\", resource=\"cpu\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory Usage in Bytes with Requests and Limits",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=~\"flexrouter\", pod=~\"$pod\", container=\"$container\", resource=\"memory\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=~\"flexrouter\", pod=~\"$pod\", container=\"$container\",  resource=\"memory\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "container_memory_working_set_bytes{namespace=~\"flexrouter\", pod =~ \"$pod\", container =~ \"$container\"}",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "$job",
   "type": "logs",
   "description": "Logs from services running in Kubernetes",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{job=~\"$job.*\"}  |~ \"$query\""
    }
   ]
  }
 ]
}