{
 "title": "K8S-Workloads-Daemonset",
 "description": "Kubernetes workloads for statefulset",
 "tags": [
  "pulse-line",
  "kubernetes",
  "statefulset",
  "workloads"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "tke",
    "label": "TKE",
    "query": "label_values(node_uname_info{}, tke_cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "daemonset",
    "label": "Daemonset",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$namespace\", workload_type=~\"daemonset\"},workload)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(container_memory_usage_bytes{container_label_io_kubernetes_pod_namespace=~\"$namespace\", container_label_io_kubernetes_pod_name=~\"$daemonset-.*\", container_label_io_kubernetes_container_name!=\"POD\"},container_label_io_kubernetes_container_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Application Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Daemonsets status",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_available{namespace=~\"$namespace\", daemonset=~\"$daemonset\"}",
     "legendFormat": "Available - {{daemonset}}"
    },
    {
     "expr": "kube_daemonset_status_number_unavailable{namespace=~\"$namespace\", daemonset=~\"$daemonset\"}",
     "legendFormat": "Unavailable - {{daemonset}}"
    }
   ]
  },
  {
   "title": "Daemonsets status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_available{tke_cluster=~\"$tke\",namespace=~\"$namespace\", daemonset=~\"$daemonset\"}",
     "legendFormat": "Available - {{daemonset}}"
    },
    {
     "expr": "kube_daemonset_status_number_unavailable{tke_cluster=~\"$tke\",namespace=~\"$namespace\", daemonset=~\"$daemonset\"}",
     "legendFormat": "Unavailable - {{daemonset}}"
    }
   ]
  },
  {
   "title": "Containers' statuses",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod=~\"$daemonset-.*\", container=~\"$container\"}",
     "legendFormat": "Ready -  {{pod}} - {{container}}"
    },
    {
     "expr": "kube_pod_container_status_running{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod=~\"$daemonset-.*\", container=~\"$container\"}",
     "legendFormat": "Running -  {{pod}} - {{container}}"
    },
    {
     "expr": "kube_pod_container_status_waiting{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod=~\"$daemonset-.*\", container=~\"$container\"}",
     "legendFormat": "Waiting -  {{pod}} - {{container}}"
    },
    {
     "expr": "kube_pod_container_status_terminated{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod=~\"$daemonset-.*\", container=~\"$container\"}",
     "legendFormat": "Terminated -  {{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "Containers' restarts total",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod=~\"$daemonset-.*\", container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "Containers' restarts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{tke_cluster=~\"$tke\",namespace=~\"$namespace\", pod=~\"$daemonset-.*\", container=~\"$container\"}",
     "legendFormat": "Restarts - {{pod}} - {{ container}}"
    }
   ]
  },
  {
   "title": "Application Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace=~\"$namespace\", container_label_io_kubernetes_pod_name=~\"$daemonset-.*\", container_label_io_kubernetes_container_name=~\"$container\"}[5m])) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "Used: {{pod_name}} - {$container}"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$daemonset-.*\", container=~\"$container\", resource=\"cpu\"}",
     "legendFormat": "Requested: {{pod}} - {$container}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (container_label_io_kubernetes_pod_name) (container_memory_usage_bytes{container_label_io_kubernetes_pod_namespace=~\"$namespace\", container_label_io_kubernetes_pod_name=~\"$daemonset-.*\", container_label_io_kubernetes_container_name=~\"$container\"})",
     "legendFormat": "Used: {{pod_name}} - {$container}"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$daemonset-.*\", container=~\"$container\", resource=\"memory\"}) by (pod)",
     "legendFormat": "Requested: {{pod}} - {$container}"
    }
   ]
  },
  {
   "title": "Traffic transmit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{container_label_io_kubernetes_pod_namespace=~\"$namespace\", container_label_io_kubernetes_pod_name=~\"$daemonset-.*\"}[5m])",
     "legendFormat": "{{interface}} : {{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Traffic receive",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{container_label_io_kubernetes_pod_namespace=~\"$namespace\", container_label_io_kubernetes_pod_name=~\"$daemonset-.*\"}[5m])",
     "legendFormat": "{{interface}} : {{container_label_io_kubernetes_pod_name}}"
    }
   ]
  }
 ]
}