{
 "title": "Nodes Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(node_boot_time_seconds,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node($instance) CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{instance=\"$instance\", mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node($instance) Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(100 * (node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemFree_bytes{instance=\"$instance\"} - node_memory_Buffers_bytes{instance=\"$instance\"} - node_memory_Cached_bytes{instance=\"$instance\"}) / node_memory_MemTotal_bytes{instance=\"$instance\"})",
     "legendFormat": "{{label_value}}"
    }
   ]
  },
  {
   "title": "Node($instance) Disk Usage",
   "type": "timeseries",
   "description": "alert in case disk usage > 90%",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100.0 - 100 * ((node_filesystem_avail_bytes{instance=\"10.242.41.189:9100\", mountpoint=\"/\", job=\"node-exporter\"} / 1000 / 1000 ) / (node_filesystem_size_bytes{instance=\"10.242.41.189:9100\", mountpoint=\"/\", job=\"node-exporter\"}  / 1024 / 1024))",
     "legendFormat": "mountpoint {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Node($instance) Network I/O Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Node($instance) CPU iowait",
   "type": "timeseries",
   "description": "alert in case cpu iowait > 60.\nAn high value usually indicates a slow/overloaded HDD or Network.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"iowait\", instance=~\"$instance\"}[5m])) by (cpu)#(sum(irate(node_cpu_seconds_total{mode=\"iowait\"}[1m]))by(node_name)  / 4)",
     "legendFormat": "cpu {{cpu}}"
    }
   ]
  },
  {
   "title": "Node($instance) Idle CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\"}[5m])) * 100)",
     "legendFormat": "cpu {{cpu}}"
    }
   ]
  },
  {
   "title": "System Load : $instance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(node_load1{instance=\"$instance\"})",
     "legendFormat": "$instance - load 1m"
    },
    {
     "expr": "sum(node_load5{instance=\"$instance\"})",
     "legendFormat": "$instance - load 5m"
    },
    {
     "expr": "sum(node_load15{instance=\"$instance\"})",
     "legendFormat": "$instance - load 15m"
    }
   ]
  },
  {
   "title": "Memory Usage: $instance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=\"$instance\"}) - sum(node_memory_MemFree_bytes{instance=\"$instance\"}) - sum(node_memory_Buffers_bytes{instance=\"$instance\"}) - sum(node_memory_Cached_bytes{instance=\"$instance\"})",
     "legendFormat": "memory used"
    },
    {
     "expr": "sum(node_memory_Buffers_bytes{instance=\"$instance\"})",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "sum(node_memory_Cached_bytes{instance=\"$instance\"})",
     "legendFormat": "memory cached"
    },
    {
     "expr": "sum(node_memory_MemFree_bytes{instance=\"$instance\"})",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": " Node details ",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\"}) by (node)",
     "legendFormat": "pod core "
    },
    {
     "expr": "sum(kube_node_status_allocatable{job=\"kube-state-metrics\", resource=\"ephemeral_storage\", unit=\"byte\"}) by (node)",
     "legendFormat": "ephemeral storage"
    },
    {
     "expr": "sum(kube_node_status_allocatable{job=\"kube-state-metrics\", resource=\"memory\", unit=\"byte\"}) by (node)",
     "legendFormat": "allocated memory"
    },
    {
     "expr": "(sum(kube_node_status_allocatable{job=\"kube-state-metrics\", resource=\"cpu\", unit=\"core\"}) by (node)) ",
     "legendFormat": "allocated memory"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\"}[5m])) by (node)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=\"kubelet\"}[5m])) by (node)",
     "legendFormat": "Transmit Rate"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\"}) by (node)",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{job=\"kubelet\"}[5m])) by (node)"
    }
   ]
  }
 ]
}