{
 "title": "Pods Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{namespace=~\"$namespace\"},pod)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(up{pod=\"$pod\"},service)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{pod=\"$pod\", namespace=\"$namespace\"},container)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU utilization %",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[5m])) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "usage / allocated"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "request / allocated"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\"}) ",
     "legendFormat": "limit / allocated"
    }
   ]
  },
  {
   "title": "Memory utilization %",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\"})) * 10000",
     "legendFormat": "usage / allocated"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\"}) )  * 10000 ##{origin_prometheus=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{origin_prometheus=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
     "legendFormat": "request / allocated"
    },
    {
     "expr": "(sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\"}) ) * 10000   ##{origin_prometheus=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{origin_prometheus=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
     "legendFormat": "limit / allocated"
    }
   ]
  },
  {
   "title": "Fix Session / Middleware Connection Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "flexrouter_fix_session{pod=\"$pod\"} or flexrouter_middleware_connection{pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilization (in core)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[5m]))",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\"})",
     "legendFormat": "request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory utilization in Bytes",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\"})",
     "legendFormat": "request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{pod=\"$pod\"} |= ``"
    }
   ]
  },
  {
   "title": "Nodes Disk Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__range])) / sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Utilization in Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[5m]))",
     "legendFormat": "Used"
    },
    {
     "expr": "container_fs_limit_bytes{container_label_io_kubernetes_pod_namespace=~\"$namespace\", container_label_io_kubernetes_pod_name=~\"$pod\", container_label_io_kubernetes_container_name=~\"$container\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU Usage % of the Limit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"\r\n\t\t\t\t\t  }[1m]\r\n\t\t)\r\n    )\r\nby (\r\n    pod,\r\n    container\r\n   ) /\r\nsum(\r\n    kube_pod_container_resource_limits\r\n    {\r\n        namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\"\r\n    } \r\n    ) by (\r\n        pod,\r\n        container\r\n    )",
     "legendFormat": "{{container_label_io_kubernetes_container_name}} in {{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Traces - Fix messages",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "filters": [
      { "id": "af6f80ee", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=~",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "!=",
       "scope": "span",
       "tag": "name",
       "value": [ "GET" ],
       "valueType": "string"
      }
     ],
     "limit": 50000,
     "spss": 10,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "CPU Usage in Cores with Requests and limit",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container!=\"POD\", pod=~\"$pod\", container=~\"$container\"}[1m])) by (pod, container)",
     "legendFormat": "{{container}} in {{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=~\"$namespace\", container!=\"POD\", pod=~\"$pod\",container=~\"$container\", resource=\"cpu\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Container Last Exit Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_exitcode{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{container}} in {{pod}}"
    }
   ]
  },
  {
   "title": "Network I/O Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}[5m]) * 8",
     "legendFormat": "Receive {{pod}}"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}[5m]) * 8",
     "legendFormat": "Transmit {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_periods_total{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"\r\n\t\t\t\t\t  }[1m]\r\n\t\t)\r\n    )\r\nby (\r\n    pod,\r\n    container\r\n   )",
     "legendFormat": "{{container_label_io_kubernetes_container_name}} in {{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "memory usage % of the limit",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\",  pod=~\"$pod\", container=~\"$container\"}) /\r\nsum(kube_pod_container_resource_limits{namespace=~\"$namespace\",  pod=~\"$pod\", container=~\"$container\", resource=\"memory\"})",
     "legendFormat": "$container in $pod"
    }
   ]
  },
  {
   "title": "Memory Usage in Bytes with Requests and Limits",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=~\"$namespace\", container != \"POD\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{container}} in {{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\",  resource=\"memory\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Packets Dropped Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_packets_dropped_total{namespace=~\"$namespace\", pod=~\"$pod\"}[1m]) * 8",
     "legendFormat": "Receive {{pod}}"
    },
    {
     "expr": "irate(container_network_transmit_packets_dropped_total{namespace=~\"$namespace\", pod=~\"$pod\"}[1m]) * 8",
     "legendFormat": "Transmit {{pod}}"
    }
   ]
  },
  {
   "title": "Pods Details",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}[5m])) by (pod)",
     "legendFormat": "Cores"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) by (pod)",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "Disk"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "Received Bytes"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "Transmitted Bytes"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "cpu request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "cpu limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\"}) by (pod)",
     "legendFormat": "memory request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\"}) by (pod)",
     "legendFormat": "memory limit"
    },
    {
     "expr": "sum by (pod) (rate(kube_pod_container_status_restarts_total{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"kube-state-metrics\"}[5m]))",
     "legendFormat": "restart"
    }
   ]
  }
 ]
}