{
 "title": "Prometheus Application",
 "description": "Overview of metrics from Prometheus 2.0.  \r\nUseful for using prometheus to monitor your prometheus.\r\nRevisions welcome!",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "job",
    "query": "label_values(prometheus_build_info,job)"
   },
   {
    "name": "instance",
    "query": "label_values(prometheus_build_info,instance)"
   },
   {
    "name": "interval",
    "query": "1h, 3h, 6h, 12h, 1d, 2d, 7d, 30d, 90d, 180d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage in Cores with Requests and limit",
   "type": "timeseries",
   "description": "CPU Usage in Cores with Requests and limit",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"prometheus.*\", container=~\"prometheus\", namespace=~\"observability\"}[1m])) by (pod, container)",
     "legendFormat": "{{container_label_io_kubernetes_container_name}} in {{container_label_io_kubernetes_pod_name}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{pod=~\"prometheus.*\", namespace=\"observability\", container=~\"prometheus\", resource=\"cpu\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{pod=~\"prometheus.*\", namespace=\"observability\", container=~\"prometheus\", resource=\"cpu\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Memory Usage in Bytes with Requests and Limits",
   "type": "timeseries",
   "description": "Memory Usage in Bytes with Requests and Limits",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"prometheus.*\", container=~\"prometheus\", namespace=~\"observability\"}",
     "legendFormat": "{{container_label_io_kubernetes_container_name}} in {{container_label_io_kubernetes_pod_name}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"observability\", pod=~\"prometheus.*\", container=\"prometheus\", resource=\"memory\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{pod=~\"prometheus.*\", namespace=\"observability\", container=~\"prometheus\", resource=\"cpu\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Total Target",
   "type": "stat",
   "description": "Current Number of discovered targets",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(up)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Target Samples",
   "type": "stat",
   "description": "the number of samples the target exposed",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(scrape_samples_scraped)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Alerts Sent",
   "type": "stat",
   "description": "Total number of alert sent in last min",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(prometheus_notifications_sent_total{job=~\"k8s\",container=\"prometheus\"}[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Head Chunks",
   "type": "stat",
   "description": "Head Chunks",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_chunks{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus Engine query / sec",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "round(irate(prometheus_engine_query_duration_seconds_count{job=\"$job\",instance=\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "start time of the Prometheus container",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"$job\", instance=\"$instance\"}*1000",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Reload time",
   "type": "stat",
   "description": "Total number of time series in prometheus",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_success_timestamp_seconds{job=\"$job\", instance=\"$instance\"}*1000",
     "legendFormat": "{{container}} {{type}}"
    }
   ]
  },
  {
   "title": "Total samples",
   "type": "stat",
   "description": "Total number of appended samples at proemtheus start to now",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_head_samples_appended_total{job=~\"$job\",instance=~\"$instance\"}[5m])) by (pod, type)",
     "legendFormat": "{{pod}} {{type}}"
    }
   ]
  },
  {
   "title": "Scrape Samples per sec",
   "type": "stat",
   "description": "Total number of appended samples. It is possible to achieve compression of 1.3 bytes per sample in production, but prefer to be conservative with 2 bytes per sample when estimating. The default retention period is 15 days, so 100,000 samples per second over 15 days is approximately 240GB. The next question is how much RAM do you need? The storage works in blocks that are written out every two hours and then compressed into larger time frames. The storage engine does not cache internally, but uses the kernel's page cache. So you need enough RAM to hold the chunks, plus the overhead, and the ones used during the query.\nHourly sample uptake is a good starting point, so 100,000 samples per second is approximately 8GB.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(prometheus_tsdb_head_samples_appended_total{job=\"$job\",instance=\"$instance\"}[1m])",
     "legendFormat": "{{container}} {{type}}"
    }
   ]
  },
  {
   "title": "Total Garbage Collector Rate (s)",
   "type": "timeseries",
   "description": "Runtime of garbage collection in the head block GC count",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_gc_duration_seconds_count{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Failure & Error [times]",
   "type": "table",
   "description": "All non-zero failures and errors",
   "gridPos": { "h": 6, "w": 17, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(net_conntrack_dialer_conn_failed_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "Failed Connections"
    },
    {
     "expr": "sum(increase(prometheus_evaluator_iterations_missed_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "Missed Iterations"
    },
    {
     "expr": "sum(increase(prometheus_evaluator_iterations_skipped_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Skipped Iterations"
    },
    {
     "expr": "sum(increase(prometheus_rule_evaluation_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Evaluation"
    },
    {
     "expr": "sum(increase(prometheus_sd_azure_refresh_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Azure Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_consul_rpc_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Consul RPC"
    },
    {
     "expr": "sum(increase(prometheus_sd_dns_lookup_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "DNS Lookup"
    },
    {
     "expr": "sum(increase(prometheus_sd_ec2_refresh_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "EC2 Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_gce_refresh_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "GCE Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_marathon_refresh_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Marathon Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_openstack_refresh_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Openstack Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_triton_refresh_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Triton Refresh"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_exceeded_sample_limit_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Sample Limit"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_duplicate_timestamp_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Duplicate Timestamp"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_bounds_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Timestamp Out of Bounds"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_order_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Sample Out of Order"
    },
    {
     "expr": "sum(increase(prometheus_treecache_zookeeper_failures_total{instance=~\"$instance\"}[5m])) > 0",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_compactions_failed_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "TSDB Compactions"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_head_series_not_found{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Series Not Found"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_reloads_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Reload"
    }
   ]
  },
  {
   "title": "Scrape Time",
   "type": "table",
   "description": "Prometheus scrape target sample required time",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk(10,scrape_duration_seconds)",
     "legendFormat": "Failed Connections"
    },
    { "expr": "topk(10,scrape_series_added)", "legendFormat": "Missed Iterations" }
   ]
  }
 ]
}