{
 "title": "Traces Pod Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values({namespace=\"flexrouter\"},namespace)"
    }
   },
   {
    "name": "pod",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Traces Generated ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 200000,
     "query": "{resource.service.name=~\"$pod\" && name!~\"GET /dapr/config|GET\"}",
     "spss": 10,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Average Time Generated ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 200000,
     "query": "{resource.service.name=~\"$pod*\" && name!~\"GET /dapr/config|GET\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Traces - Fix messages",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "af6f80ee", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=~",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "simple-ofp-fix-gateway-ofp2" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "!=",
       "scope": "span",
       "tag": "name",
       "value": [ "GET" ],
       "valueType": "string"
      }
     ],
     "limit": 50000,
     "query": "{resource.service.name=~\"$pod\" && name!~\"GET /dapr/config|GET\"}",
     "spss": 10,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Min Time Generated ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 200000,
     "query": "{resource.service.name=~\"$pod\" && name!~\"GET /dapr/config|GET\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Max Time Generated ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 200000,
     "query": "{resource.service.name=~\"$pod\" && name!~\"GET /dapr/config|GET\" }",
     "tableType": "traces"
    }
   ]
  }
 ]
}