{
 "title": "Traces Overview",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Traces Generated by OTC Fix",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 200000,
     "query": "{resource.service.name=~\"otc-fix-gateway-.*\" && name!~\"GET /dapr/config|GET\"}",
     "spss": 10,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Traces Generated by OFP Fix",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 200000,
     "query": "{resource.service.name=~\"simple-ofp-fix-gateway-.*\" && name!~\"GET /dapr/config|GET\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Traces - Fix messages",
   "type": "table",
   "gridPos": { "h": 25, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "af6f80ee", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=~",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "simple-ofp-fix-gateway-ofp2" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "!=",
       "scope": "span",
       "tag": "name",
       "value": [ "GET" ],
       "valueType": "string"
      }
     ],
     "limit": 50000,
     "query": "{resource.service.name=~\".\" && name!~\"GET /dapr/config|GET\"}",
     "spss": 10,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Traces Generated by OTC 1 Fix",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 200000,
     "query": "{resource.service.name=~\"otc-fix-gateway-otc1\" && name!~\"GET /dapr/config|GET\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Traces Generated by OTC 2 Fix",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 200000,
     "query": "{resource.service.name=~\"otc-fix-gateway-otc2\" && name!~\"GET /dapr/config|GET\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Traces Generated by CDX 1 Fix",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 200000,
     "query": "{resource.service.name=~\"otc-fix-gateway-cdx1\" && name!~\"GET /dapr/config|GET\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Traces Generated by OFP 1 Fix",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 200000,
     "query": "{resource.service.name=~\"simple-ofp-fix-gateway-ofp1\" && name!~\"GET /dapr/config|GET\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Traces Generated by OFP 2 Fix",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 200000,
     "query": "{resource.service.name=~\"simple-ofp-fix-gateway-ofp2\" && name!~\"GET /dapr/config|GET\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Min Time Generated by OTC FixTraces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 200000,
     "query": "{resource.service.name=~\"otc-fix-gateway-.*\" && name!~\"GET /dapr/config|GET\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Max Time Generated by OTC FixTraces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 200000,
     "query": "{resource.service.name=~\"otc-fix-gateway-.*\" && name!~\"GET /dapr/config|GET\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Min Time Generated by OFP FixTraces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 200000,
     "query": "{resource.service.name=~\"simple-ofp-fix-gateway-.*\" && name!~\"GET /dapr/config|GET\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Min Time Generated by OFP FixTraces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 200000,
     "query": "{resource.service.name=~\"simple-ofp-fix-gateway-.*\" && name!~\"GET /dapr/config|GET\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Average Time Generated by OTC FixTraces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 200000,
     "query": "{resource.service.name=~\"otc-fix-gateway-.*\" && name!~\"GET /dapr/config|GET\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Average Time Generated by OFP Fix Traces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 200000,
     "query": "{resource.service.name=~\"simple-ofp-fix-gateway-.*\" && name!~\"GET /dapr/config|GET\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Avg Time Generated by OTC 1 Traces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 200000,
     "query": "{resource.service.name=~\"otc-fix-gateway-otc1\" && name!~\"GET /dapr/config|GET\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Avg Time Generated by OTC 2 Traces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 200000,
     "query": "{resource.service.name=~\"otc-fix-gateway-otc2\" && name!~\"GET /dapr/config|GET\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Avg Time Generated by OFP 1 Traces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 200000,
     "query": "{resource.service.name=~\"simple-ofp-fix-gateway-ofp1\" && name!~\"GET /dapr/config|GET\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Avg Time Generated by OFP 2 Traces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 200000,
     "query": "{resource.service.name=~\"simple-ofp-fix-gateway-ofp2\" && name!~\"GET /dapr/config|GET\" }",
     "tableType": "traces"
    }
   ]
  }
 ]
}