replicaCount: 1

# Multiple instances configuration
instances:
  enabled: true
  count: 4
  namePattern: "appender-java-%02d"  # Format: appender-java-01, appender-java-02, etc.
  basePort: 8080  # Base port for the first instance, subsequent instances will use basePort + instanceIndex

image:
  repository: achalbi/appender-java
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 20
  periodSeconds: 5

ingress:
  enabled: true
  host: dev.example.com 
  annotations: {}
  ingressClassName: nginx

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 100m

springProfilesActive: prod

otelAutoInstrumentation:
  enabled: "true"
  instrumentationName: java-instrumentation
  namespace: appender-java-dev
  exporterEndpoint: http://opentelemetry-collector.observability:4317
  javaAgentImage: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
