replicaCount: 1

# Multiple instances configuration
instances:
  enabled: true
  count: 4
  namePattern: "appender-java-%02d"  # Format: appender-java-01, appender-java-02, etc.
  basePort: 8080  # Base port for the first instance, subsequent instances will use basePort + instanceIndex

image:
  repository: achalbi/appender-java
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 20
  periodSeconds: 5

ingress:
  enabled: false
  host: ""
  annotations: {}

# OpenTelemetry configuration
opentelemetry:
  enabled: true
  endpoint: "http://opentelemetry-collector.observability.svc.cluster.local:4317"
  serviceName: "appender-java"
  serviceVersion: "1.0.0"


# Resource limits and requests
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Affinity and tolerations
affinity: {}
tolerations: []
nodeSelector: {}

# Service account
serviceAccount:
  create: true
  name: ""

springProfilesActive: prod

otelAutoInstrumentation:
  enabled: "true"
  instrumentationName: java-instrumentation
  namespace: dev-appender-java
  exporterEndpoint: http://opentelemetry-collector.dev-observability:4317
  javaAgentImage: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
