environments:
  production:
    values:
      - replicaCount: 3
      - image:
          tag: "stable"
      - ingress:
          enabled: true
          host: app.example.com

---
releases:
  # Pre-install chart - sets up prerequisites
  - name: pre-install
    namespace: prod-appender-java
    createNamespace: true
    chart: ../../charts/pre-install
    values:
      - ../../values/pre-install/values.dev.yaml

  # Appender Java application
  - name: appender-java
    namespace: prod-appender-java
    createNamespace: true
    chart: ../../charts/appender-java
    needs:
      - prod-appender-java/pre-install
    values:
      - ../../values/appender-java/values.yaml
      - replicaCount: 2
      - instances:
          enabled: true
          count: 10
          namePattern: "appender-java-%02d"
          basePort: 8080
      - image:
          repository: achalbi/appender-java
          tag: "stable"
      - service:
          type: ClusterIP
          port: 8080
      - ingress:
          enabled: true
          host: app.example.com
      - opentelemetry:
          enabled: true
          endpoint: "http://opentelemetry-collector.observability.svc.cluster.local:4317"
          serviceName: "appender-java-prod"
      - resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi 