apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector
  namespace: observability
spec:
  type: NodePort
  selector: 
    app.kubernetes.io/instance: opentelemetry-collector
    app.kubernetes.io/name: opentelemetry-collector
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    nodePort: 30097    # may choose any free port >30000
  - name: otlp-http
    port: 4318
    targetPort: 4318
    nodePort: 30098