tempo:
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal
  server:
    http_listen_port: 3200
  distributor:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
  ingester:
    max_block_bytes: 1000000         # Remove underscores
    max_block_duration: 5m
  compactor:
    compaction:
      block_retention: 1h
  metrics_generator:
    enabled: false

persistence:
  enabled: true
  storageClassName: ""
  accessMode: ReadWriteOnce
  size: 10Gi

serviceMonitor:
  enabled: true
  interval: 30s
