{{- if .Values.instances.enabled }}
{{- range $index := until (.Values.instances.count | int) }}
{{- $instanceIndex := add $index 1 }}
{{- $instanceName := printf $.Values.instances.namePattern $instanceIndex }}
# {{- $instancePort := add $.Values.instances.basePort $index }}
{{- $instancePort := $.Values.instances.basePort }}
{{- $isFirst := eq $instanceIndex 1 }}
{{- $isLast := eq $instanceIndex ($.Values.instances.count | int) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $instanceName }}
  labels:
    {{- include "appender-java.labels" $ | nindent 4 }}
    app.kubernetes.io/instance: {{ $instanceName }}
    app.kubernetes.io/instance-index: {{ $instanceIndex | quote }}
  {{- if $.Values.otelAutoInstrumentation.enabled }}
  annotations:
    instrumentation.opentelemetry.io/inject-java: "true"
    instrumentation.opentelemetry.io/instrumentation: "{{ $.Values.otelAutoInstrumentation.instrumentationName }}"
  {{- end }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "appender-java.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/instance: {{ $instanceName }}
  template:
    metadata:
      labels:
        {{- include "appender-java.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/instance: {{ $instanceName }}
        app.kubernetes.io/instance-index: {{ $instanceIndex | quote }}
    spec:
      containers:
      - name: {{ $.Chart.Name }}
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ $instancePort }}
          protocol: TCP
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTANCE_INDEX
          value: {{ $instanceIndex | quote }}
        - name: INSTANCE_NAME
          value: {{ $instanceName | quote }}
        - name: NODE_TYPE
          value: {{ if $isFirst }}"begin"{{ else if $isLast }}"end"{{ else }}"link"{{ end }}
        - name: SPRING_PROFILES_ACTIVE
          value: {{ $.Values.springProfilesActive | quote }}
        {{- if not $isLast }}
        {{- $nextInstanceIndex := add $instanceIndex 1 }}
        {{- $nextInstanceName := printf $.Values.instances.namePattern $nextInstanceIndex }}
        {{- $nextInstancePort := $.Values.instances.basePort }}
        - name: TARGET_URL
          value: "http://{{ $nextInstanceName }}-service.{{ $.Release.Namespace }}.svc.cluster.local:{{ $nextInstancePort }}/append"
        {{- end }}
        {{- if $.Values.resources }}
        resources:
          {{- toYaml $.Values.resources | nindent 10 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          initialDelaySeconds: {{ $.Values.livenessProbe.initialDelaySeconds | default 30 }}
          periodSeconds: {{ $.Values.livenessProbe.periodSeconds | default 10 }}
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: {{ $.Values.readinessProbe.initialDelaySeconds | default 20 }}
          periodSeconds: {{ $.Values.readinessProbe.periodSeconds | default 5 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $instanceName }}-service
  labels:
    {{- include "appender-java.labels" $ | nindent 4 }}
    app.kubernetes.io/instance: {{ $instanceName }}
    app.kubernetes.io/instance-index: {{ $instanceIndex | quote }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $instancePort }}
      targetPort: http
      nodePort: {{ $.Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "appender-java.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/instance: {{ $instanceName }}
{{- end }}
{{- end }} 