{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "appender-java.serviceAccountName" . }}
  labels:
    {{- include "appender-java.labels" . | nindent 4 }}
{{- end }} 
 