repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: jetstack
    url: https://charts.jetstack.io

environments:
  dev:
    values:
      - envPrefix: dev-
  prod:
    values:
      - envPrefix: prod-
---
releases:
  - name: "{{ .Values.envPrefix }}cert-manager"
    namespace: "{{ .Values.envPrefix }}cert-manager"
    createNamespace: true
    chart: jetstack/cert-manager
    version: v1.18.1
    set:
      - name: installCRDs
        value: true
      - name: fullnameOverride
        value: "cert-manager" 